// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe          = require("reason-react/src/ReactDOMRe.js");
var ReasonReact         = require("reason-react/src/ReasonReact.js");
var World$ReactTemplate = require("./World.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, World$ReactTemplate.make(/* array */[])), "index");

/*  Not a pure module */
